# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a64b6e76f9a7dad9581f9b462405c9b9b0b49982abe5954f76b7d89f5a789bb6ddfbc7ad8a6dc5884a84c772e4893907cc35f544c11962b51e6f52379a5fc9a4

test:
  secret_key_base: 86a3463e4d54fad72e2f3fafefdab8650d6c91e5ddbfb81d365e7516daa1d1102b19293ebfa9d228c529068144b37dffb2d34f998d44799d674f1d16e9e6ba63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
